### ISSUE TITLE
Can u send the decompression password of pre-training model package(checkPoint.rar) ?

### ISSUE THREAD

**Issue by feiyun1265** [enkiwang/Imperceptible-fake-face-antiforensic#1]
Can u send the decompression password of pre-training model package(checkPoint.rar) ?
Thanks!

**Comment by enkiwang** [comment]
> Can u send the decompression password of pre-training model package(checkPoint.rar) ? Thanks!
Hi, please try unzipping files via: 
1) for checkPoints: >Su&U/g~8F6V)/D}

2) for test data: bkju>EP&jA245N`+
